proc report data=rap.sprzedaz nowd;
column (kod nazwisko, (liczba) liczba2 text suma);
define nazwisko / across;
define kod / group format=$10. 'Region';
define liczba / analysis sum;
define liczba2 / computed;
define text / computed;
define suma / computed;
compute after;
line 57*'-';
line  '***' _c2_ 10.2 '****';
line  '***' _c3_ 10.2 '****';
endcomp;
compute liczba2;
liczba2=sum(_c2_,_c3_,2);
endcomp;
compute text;
if _c3_>5 then text=100;
else text=0;
endcomp;
compute suma;
suma=liczba2+text;
endcomp;
rbreak after / ol summarize;
run;